### PR TITLE
Move to CLI/bin approach

### PR DESCRIPTION
**Pull request by janniks**

### CODE REVIEW

**Comment by janniks** [comment]
@coolaj86 I released a preview as `2.0.0-beta`

Can be tested via npx with the `-p` package specifier:
```
npx -p basetag@2.0.0-beta basetag
npx -p basetag@2.0.0-beta basetag link
npx -p basetag@2.0.0-beta basetag link
```

**Comment by janniks** [comment]
Unfortunately, the `postinstall` tag only works for packages that are being installed.
i.e. when we use `postinstall` in projects that are supposed to be used with `basetag` (e.g. project-alice), that `postinstall` script is not executed whenever dependencies are installed via `npm install` for projects-allice. But rather when somebody installs project-alice as a dependency...

I found an alternative though:
- https://stackoverflow.com/a/51155609/1139105
- https://docs.npmjs.com/cli/v6/using-npm/scripts#hook-scripts

I will try to integrate this into the basetag `link` command this week.

**Comment by coolaj86** [comment]
> Unfortunately, the `postinstall` tag only works for packages that are being installed.

If I have `{ "postinstall": "npx basetag" }` in my own `package.json`, and it works as expected. Every time I run `npm install`, `npx basetag` runs after, putting the link back in place.

**Comment by coolaj86** [comment]
I haven't tried this out yet, but it looks like `.hooks/postinstall` is equivalent to `package.json.scripts.postinstall` from the description.

**Comment by janniks** [comment]
Interesting, I thought I tried that earlier. I coukd swear it doesn't work. Will try again tomorrow

**Comment by janniks** [comment]
Can you somehow provide me with an example that works? I have tried a bunch of times now and it doesn't seem to work for me... Using npm v6.14.11

According to [1](https://stackoverflow.com/questions/44362462/how-to-run-a-post-install-script-after-every-npm-install-package-run) and [2](https://docs.npmjs.com/cli/v6/using-npm/scripts) this doesn't work but rather the `.hooks` have to be used...

**Comment by coolaj86** [comment]
For reference, we continued and resolved this conversation in https://github.com/janniks/basetag/pull/21

I see that #21 was merged into https://github.com/janniks/basetag/tree/add-bin-structure, but that's not yet in master. Is that waiting for something?

**Comment by janniks** [comment]
Thanks for the ping and sorry for taking so long. I'll look into this tomorrow — haven't had a lot of spare time in the last two weeks, but I should be somewhat free now.

I'll add one more small fix and push a new version tomorrow

**Comment by janniks** [comment]
I think this looks decent... 😬

I've added
- the relative path default #24 (and an `--absolute` flag to override)
- a `npx basetag <action>` structure with `link` and `rebase` so far

**Comment by janniks** [comment]
Deployed via `v2.0.0` — @coolaj86 would love to hear your feedback, I think everything should work 👀

**Pull request merged**
